### ISSUE TITLE
No access to documentation

### ISSUE THREAD

**Issue by czesio** [saleweaver/python-amazon-sp-api#1190]
**Describe the bug**
Website with documentation (https://sp-api-docs.saleweaver.com/) is not available

**Comment by chile-atlas** [comment]
Same issue, @dev kindly check the docs

**Comment by saleweaver** [comment]
I merged the PR, I'm currently away, docs go back online next week. Sorry for the inconvenience

**Comment by yinizhilian** [comment]
Website with documentation (https://sp-api-docs.saleweaver.com/) is not available

**Comment by Blochergroup** [comment]
Unfortunately still not available

**Comment by verajs** [comment]
Hey @saleweaver, we've noticed the documentation (https://sp-api-docs.saleweaver.com/) still isn't available. I completely understand that the holidays are around the corner, and it's a time for family and relaxation. However, we're here to help. If there's any way we can assist, whether it's covering some costs or helping with development challenges, please let us know. I know a lot of us would be glad to collaborate.

**Comment by tgehrs** [comment]
Docs are now available at https://python-amazon-sp-api.readthedocs.io/en/latest/index.html
